Wade adjustments
tum-esi/testbench pull request #61
Opened 2023-06-02 19:26 UTC by hasanheroglu

2023-06-03 18:42 UTC, egekorkan requested changes
Code changes are good but there are questions about two files

2023-06-03 18:42 UTC, egekorkan commented on src/defaults.ts
is this needed if we also have assets/default-config.json ?

2023-06-05 06:56 UTC, hasanheroglu commented on src/defaults.ts
It is the other way around. Since we had problems with paths, we put usernames, passwords, and default config to a typescript file instead of accessing the file system. Removed default-config.json, username, and password files @fa783be

2023-06-05 07:00 UTC, hasanheroglu commented on scripts/postinstall.js
That's what I thought too, but when we include the testbench in WADE, we get the library error if we don't run on the testbench too. We might not need it if we start installing testbench from npm instead of linking it locally.

2023-06-05 09:03 UTC, egekorkan commented on scripts/postinstall.js
Ok let's remove it for now. I will publish a new version of the test bench on npm after merging this PR.

2023-06-05 09:04 UTC, egekorkan commented on scripts/postinstall.js
Even without doing that, we should test even a git install (still in package.json) causes the problem.

2023-06-05 09:12 UTC, hasanheroglu commented on scripts/postinstall.js
Removed it

2023-06-05 14:16 UTC, merged